### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by elsalvadordali**
I actually finished the design. It's still not mobile friendly, doesn't include the google calendar API, needs a discord link, and needs the members/admin images, but it's done!
Screenshot 2023-03-07 at 11-25-59 React App

(screenshot)

### CODE REVIEW

**Comment by readysetagile** [comment]
@elsalvadordali there are 3 failing tests with `npm test`.  Since we are coming from the testing branch we should get these to pass.  

For now, you can use [https://discord.gg/](https://discord.gg/) for the Discord link

**Comment by readysetagile** [comment]
we decided last night that we would close this pull request, start a new branch (copying the changes from this branch), and create a new PR into `dev`

**Comment by readysetagile** [comment]
OK -- so I am re-opening this PR to include into dev.  so, @elsalvadordali it looks like we need to resolve the broken tests that you created :) ... or would it be easier to close this PR and create a new branch with the copied code like we discussed.  you tell me.

**Comment by jduffey** [comment]
I forked the repo and made another branch to play around with some changes and fixes to the tests: https://github.com/jduffey/cbus-web/commits/testing-jed

I haven't made any moves to merge any of this into the FCCCols repo since I don't have a full understanding of what all this branch was meant to cover and whether we want to continue to write tests before merging it.

@elsalvadordali Happy to collab w/ you and go over the code changes and/or discuss other changes intended for the scope of this branch.

**Comment by jduffey** [comment]
With discussion/input from John and Tiana, recommend closing this PR upon merging https://github.com/FCCColumbus/cbus-web/pull/36 (this new PR retains Tiana's commits and should credit her when merged to dev)

**Pull request merged**
