### PR TITLE
Implement Tiana's new design

### PR DESCRIPTION
**Pull request by jduffey**
This PR builds off Tiana's "testing" branch here: https://github.com/FCCColumbus/cbus-web/pull/35

UX-wise:
- Replaces the static homepage image with more of a structured website

Code-wise:
- Improves file structure by moving components and tests into folders
- Implements snapshot tests for all components

Notes:
- The "Events" section displays placeholder text, intended to be later replaced with an API integration with something like Google Calendar or Meetup.com
- Tests are far from comprehensive and serve as more of a starting point/template for building future tests
- Per discussion with John on May 17, this PR obviates the need for this branch: https://github.com/FCCColumbus/cbus-web/tree/feature/codejam

### CODE REVIEW

**Comment by jduffey** [comment]
👀 👀 👀 
👉  NOTE: as part of reviewing/merging this PR:

- Close this PR: https://github.com/FCCColumbus/cbus-web/pull/35
- Delete this branch: https://github.com/FCCColumbus/cbus-web/tree/feature/codejam

**Comment by readysetagile** [comment]
the code and page look awesome.

Only problem is that one test is failing, and I can't figure out why.  Diff looks fine to me 🤔 

```
 FAIL  src/test/components/Event.test.js
  Event
    × renders (29 ms)

  ● Event › renders

    expect(received).toMatchSnapshot()

    Snapshot name: `Event renders 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -17,11 +17,11 @@
              <tr>
                <th>
                  time:
                </th>
                <td>
    -             Apr 17, 2023, 6:30 PM
    +             Apr 17, 2023, 6:30 PM
                </td>
              </tr>
              <tr>
                <th>
                  location:

      13 |
      14 |     const view = renderer.create(<Event event={event} />);
    > 15 |     expect(view).toMatchSnapshot();
         |                  ^
      16 |   });
      17 | });
      18 |

      at Object.<anonymous> (src/test/components/Event.test.js:15:18)

 › 1 snapshot failed.
```

**Comment by jduffey** [comment]
> the code and page look awesome.
> 
> Only problem is that one test is failing, and I can't figure out why. Diff looks fine to me 🤔
> 
> ```
>  FAIL  src/test/components/Event.test.js
>   Event
>     × renders (29 ms)
> 
>   ● Event › renders
> 
>     expect(received).toMatchSnapshot()
> 
>     Snapshot name: `Event renders 1`
> 
>     - Snapshot  - 1
>     + Received  + 1
> 
>     @@ -17,11 +17,11 @@
>               <tr>
>                 <th>
>                   time:
>                 </th>
>                 <td>
>     -             Apr 17, 2023, 6:30 PM
>     +             Apr 17, 2023, 6:30 PM
>                 </td>
>               </tr>
>               <tr>
>                 <th>
>                   location:
> 
>       13 |
>       14 |     const view = renderer.create(<Event event={event} />);
>     > 15 |     expect(view).toMatchSnapshot();
>          |                  ^
>       16 |   });
>       17 | });
>       18 |
> 
>       at Object.<anonymous> (src/test/components/Event.test.js:15:18)
> 
>  › 1 snapshot failed.
> ```

So my first instinct is that this is probably some weird formatting/encoding issue having to do with time (normally there's NEVER an issue with dates and times, right? 😉 ) I pasted your output into VS Code and noticed there's no whitepsace indicator in the "expected" value:

Screenshot 2023-05-22 at 4 50 51 PM

Then I saved the output to a file and opened it in Hex Fiend (http://hexfiend.com/) to get a better idea of what exactly is going on:

Screenshot 2023-05-22 at 4 48 15 PM

The "expected" value contains a `E280AF` character, which is apparently something called a "Narrow No-Break Space" 😛 : https://www.fileformat.info/info/unicode/char/202f/index.htm. This does make sense because normally you are treating "6:30 PM" as a single string that shouldn't be broken before the AM/PM.

As a workaround I'm going to replace the problematic character with a regular space and add a comment in the code about why. For reference this does appear to be a relatively recent change in Node: https://www.reddit.com/r/webdev/comments/1054ve6/psa_node_1813_changed_datetime_formatting/

**Review by readysetagile — APPROVED** [review]
Wow that "Narrow No-Break Space" date formatting thing was a "needle in a haystack find".  I like that we removed the JS call from the actual component rendering and put it in a separate function.  I do foresee the need refactor the `formattedDateTime` and `replacedNonBreakingSpace` call into a more globally available js file.  For now it's fine, tho, since the only place we will see dates is our own events.  The comments in code help.

**Comment by readysetagile** [comment]
`feature/codejam` deleted

**Pull request merged**
